# Generated by Django 6.1 on 2026-08-28 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cleaning", "Teeth Cleaning"),
                            ("teeth_whitening", "Teeth Whitening"),
                            ("teeth_polishing", "Teeth Polishing"),
                            ("teeth_filling", "Teeth Filling"),
                            ("extraction", "Tooth Extraction"),
                            ("dental_implants", "Dental Implants"),
                            ("crown_and_bridge", "Crown and Bridge"),
                            ("complete_denture", "Complete Denture"),
                            ("orthodontics", "Orthodontics"),
                            ("root_canal_treatment", "Root Canal Treatment(RCT)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("message", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("paid", models.BooleanField(default=False)),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("email", models.CharField(max_length=122)),
                ("phone", models.CharField(max_length=12)),
                ("subject", models.CharField(blank=True, max_length=122)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("rating", models.IntegerField(default=0)),
            ],
        ),
    ]
