# Generated by Django 6.1 on 2026-08-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_feedback_is_approved_doctorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
