# Generated by Django 5.2.15 on 2026-09-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_appointment_id_alter_contact_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cleaning", "Teeth Cleaning"),
                    ("teeth_whitening", "Teeth Whitening"),
                    ("teeth_polishing", "Teeth Polishing"),
                    ("teeth_filling", "Teeth Filling"),
                    ("extraction", "Tooth Extraction"),
                    ("dental_implants", "Dental Implants"),
                    ("crown_and_bridge", "Crown and Bridge"),
                    ("complete_denture", "Complete Denture"),
                    ("orthodontics", "Orthodontics"),
                    ("root_canal_treatment", "Root Canal Treatment (RCT)"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=122),
        ),
    ]
